<?php

namespace Modules\Tour\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Modules\Core\Models\Attributes;
use Modules\Location\Models\Location;
use Modules\Report\Helpers\SearchHistoryHelper;
use Modules\Tour\Models\Tour;
use Modules\Tour\Models\TourCategory;

class TourController extends Controller
{
    protected $tourClass;

    protected $locationClass;

    protected $tourCategoryClass;

    protected $attributesClass;

    public function __construct(Tour $tour)
    {
        $this->tourClass = $tour;
        $this->locationClass = Location::class;
        $this->tourCategoryClass = TourCategory::class;
        $this->attributesClass = Attributes::class;
    }

    public function callAction($method, $parameters)
    {
        if (setting_item('tour_disable')) {
            return redirect('/');
        }

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $is_ajax = $request->query('_ajax');

        // Record search history if there's a search keyword
        $searchKeyword = $request->input('s') ?? $request->input('search') ?? $request->input('keyword') ?? $request->input('location_name');
        if (! empty($searchKeyword)) {
            SearchHistoryHelper::record($searchKeyword);
        }

        if (! empty($request->query('limit'))) {
            $limit = $request->query('limit');
        } else {
            $limit = ! empty(setting_item('tour_page_limit_item')) ? setting_item('tour_page_limit_item') : 9;
        }
        $query = $this->tourClass->search($request->input());
        $list = $query->paginate($limit);

        $markers = [];
        if (! empty($list)) {
            foreach ($list as $row) {
                $markers[] = [
                    'id' => $row->id,
                    'title' => $row->title,
                    'lat' => (float) $row->map_lat,
                    'lng' => (float) $row->map_lng,
                    'gallery' => $row->getGallery(true),
                    'infobox' => view('Tour::frontend.layouts.search.loop-grid', ['row' => $row, 'disable_lazyload' => 1, 'wrap_class' => 'infobox-item'])->render(),
                    'marker' => get_file_url(setting_item('tour_icon_marker_map'), 'full') ?? url('images/icons/png/pin.png'),
                ];
            }
        }
        $limit_location = 15;
        if (empty(setting_item('space_location_search_style')) or setting_item('space_location_search_style') == 'normal') {
            $limit_location = 1000;
        }
        $data = [
            'rows' => $list,
            'tour_category' => $this->tourCategoryClass::where('status', 'publish')->with(['translation'])->get()->toTree(),
            'tour_location' => $this->locationClass::where('status', 'publish')->with(['translation'])->limit($limit_location)->get()->toTree(),
            'tour_min_max_price' => $this->tourClass::getMinMaxPrice(),
            'markers' => $markers,
            'blank' => setting_item('search_open_tab') == 'current_tab' ? 0 : 1,
            'seo_meta' => $this->tourClass::getSeoMetaForPageList(),
        ];
        $layout = setting_item('tour_layout_search', 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        $data['layout'] = $layout;
        if ($is_ajax) {
            return $this->sendSuccess([
                'html' => view('Tour::frontend.layouts.search-map.list-item', $data)->render(),
                'markers' => $data['markers'],
            ]);
        }
        $data['attributes'] = $this->attributesClass::where('service', 'tour')->orderBy('position', 'desc')->with(['terms', 'translation'])->get();
        if ($layout == 'map') {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';

            return view('Tour::frontend.search-map', $data);
        }

        return view('Tour::frontend.search', $data);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->tourClass::where('slug', $slug)->with(['location', 'translation', 'hasWishList'])->first();
        if (empty($row) or ! $row->hasPermissionDetailView()) {
            return redirect('/');
        }

        // Increment visitors count for this tour
        $this->incrementVisitors($row);

        // Record visit as search history
        $translation = $row->translate();
        if ($translation && ! empty($translation->title)) {
            SearchHistoryHelper::record($translation->title);
        }

        $tour_related = [];

        // dd($row);
        $location_id = $row->location_id;
        $category_id = $row->category_id;
        if (! empty($category_id)) {
            $tour_related = $this->tourClass::where('category_id', $category_id)->where('status', 'publish')->take(4)->whereNotIn('id', [$row->id])->with(['location', 'translation', 'hasWishList'])->get();
        }
        $review_list = $row->getReviewList();
        $data = [
            'row' => $row,
            'translation' => $translation,
            'tour_related' => $tour_related,
            'booking_data' => $row->getBookingData(),
            'review_list' => $review_list,
            'seo_meta' => $row->getSeoMetaWithTranslation(app()->getLocale(), $translation),
            'body_class' => 'is_single',
            'breadcrumbs' => [
                [
                    'name' => __('Tour'),
                    'url' => route('tour.search'),
                ],
            ],
        ];
        $data['breadcrumbs'] = array_merge($data['breadcrumbs'], $row->locationBreadcrumbs());
        $data['breadcrumbs'][] = [
            'name' => $translation->title,
            'class' => 'active',
        ];
        $this->setActiveMenu($row);

        // dd($data);
        return view('Tour::frontend.detail', $data);
    }

    /**
     * Increment visitors count for a tour (prevents duplicate counting per session)
     */
    protected function incrementVisitors(Tour $tour): void
    {
        $sessionKey = 'tour_visited_'.$tour->id;

        // Check if user has already visited this tour in this session
        if (! session()->has($sessionKey)) {
            // Increment visitors count
            $currentVisitors = (int) ($tour->visitors ?? 0);
            $tour->visitors = $currentVisitors + 1;
            $tour->timestamps = false; // Don't update updated_at
            $tour->save();

            // Mark as visited in session (expires with session)
            session()->put($sessionKey, true);
        }
    }

    /**
     * Perform AJAX search for tours.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function searchAjax(Request $request)
    {
        $query = $request->input('query', ''); // Retrieve the 'query' parameter from the request
        $limit = $request->input('limit', 1000); // Default limit for pagination

        // Search locations based on name
        $locationQuery = Location::where('name', 'like', '%'.$query.'%')
            ->whereNull('deleted_at')
            ->paginate($limit);

        // Search tours based on title
        $tourQuery = Tour::where('title', 'like', '%'.$query.'%')
            ->whereNull('deleted_at')
            ->paginate($limit);

        $tours = [];
        foreach ($locationQuery as $row) {
            $title = strlen($row->name) > 25 ? substr($row->name, 0, 25).'...' : $row->name; // Limit title to 25 characters
            $image_url = get_file_url($row->image_id, 'full'); // Get the full URL of the image
            $tours[] = [
                'title' => $title, // Assuming 'name' is the attribute representing the location name
                'location' => '', // No location details for locations
                'slug' => '?location_id='.$row->id,
                'image_url' => $image_url, // No image URL for locations
                // 'info' => [$row],
                'model' => 'location', //
            ];
        }
        // Process tour results
        foreach ($tourQuery as $row) {
            $title = strlen($row->title) > 25 ? substr($row->title, 0, 25).'...' : $row->title; // Limit title to 25 characters
            $image_url = get_file_url($row->image_id, 'full'); // Get the full URL of the image

            $tours[] = [
                'title' => $title,
                'location' => $row->location ? ', '.$row->location->name : '',
                'slug' => $row->slug,
                'image_url' => $image_url,
                'model' => 'tour',
            ];
        }

        // Process location results

        // dd( $tours);
        return response()->json([
            'tours' => $tours,
        ]);
    }
}
