<?php

namespace Modules\Coupon\Admin;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Modules\AdminController;
use Modules\Booking\Models\Service;
use Modules\Coupon\Models\Coupon;
use Modules\Coupon\Models\CouponServices;

class CouponController extends AdminController
{
    public function delete($id, Request $request)
    {
        $this->checkPermission('coupon_delete');
        $coupon = Coupon::find($id);
        if (! $coupon) {
            return redirect()->back()->with('error', __('Coupon not found.'));
        }
        $coupon->delete();

        return redirect()->back()->with('success', __('Coupon deleted successfully.'));
    }

    public function __construct()
    {
        $this->setActiveMenu(route('coupon.admin.index'));
    }

    public function callAction($method, $parameters)
    {
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('coupon_view');

        $query = Coupon::query();

        // Search by name or code
        if ($s = $request->input('s')) {
            $query->where(function ($q) use ($s) {
                $q->where('name', 'LIKE', "%$s%")
                    ->orWhere('code', 'LIKE', "%$s%");
            });
        }

        // Date range filter (created_at)
        if ($from = $request->input('from')) {
            $query->whereDate('created_at', '>=', $from);
        }
        if ($to = $request->input('to')) {
            $query->whereDate('created_at', '<=', $to);
        }

        // Status filter (active/inactive)
        if ($active = $request->input('active')) {
            $query->where('status', $active == '1' ? 'publish' : 'draft');
        }

        // Discount type filter
        if ($discount_type = $request->input('discount_type')) {
            $query->where('discount_type', $discount_type);
        }

        // Apply Coupon To filter
        if ($apply_to = $request->input('apply_to')) {
            $query->where('apply_to', $apply_to);
        }

        // Redeemed date range (from booking coupons)
        if ($redeemed_from = $request->input('redeemed_from')) {
            $query->whereHas('bookings', function ($q) use ($redeemed_from) {
                $q->whereDate('created_at', '>=', $redeemed_from);
            });
        }
        if ($redeemed_to = $request->input('redeemed_to')) {
            $query->whereHas('bookings', function ($q) use ($redeemed_to) {
                $q->whereDate('created_at', '<=', $redeemed_to);
            });
        }

        // Redeemed checkbox
        if ($request->input('redeemed')) {
            $query->whereHas('bookings', function ($q) {
                $q->whereNotIn('booking_status', ['draft', 'unpaid', 'cancelled']);
            });
        }

        // Extra Discount checkbox (assume amount > X, adjust as needed)
        if ($request->input('extra_discount')) {
            $query->where('amount', '>', 100); // Example threshold
        }

        // Available checkbox (not expired and not used up)
        if ($request->input('available')) {
            $query->where(function ($q) {
                $q->whereNull('end_date')->orWhere('end_date', '>', now());
            });
            $query->where(function ($q) {
                $q->whereNull('quantity_limit')->orWhereRaw('(SELECT COUNT(*) FROM bravo_booking_coupons WHERE coupon_code = bravo_coupons.code AND booking_status NOT IN ("draft","unpaid","cancelled")) < quantity_limit');
            });
        }

        $query->orderBy('id', 'desc');

        $data = [
            'rows' => $query->paginate(20),
            'breadcrumbs' => [
                [
                    'name' => __('Coupon Management'),
                    'class' => 'active',
                ],
            ],
            'page_title' => __('Coupon Management'),
        ];

        // Add activity (service) name for display in index table
        if (! empty($data['rows'])) {
            $data['rows']->getCollection()->transform(function ($item) {
                $first = $item->couponServices()->first();
                if (! empty($first)) {
                    $service = Service::find($first->service_id);
                    $item->activity_name = $service ? $service->title : null;
                } else {
                    $item->activity_name = null;
                }

                return $item;
            });
        }

        return view('Coupon::admin.index', $data);
    }

    public function edit(Request $request, $id)
    {
        $this->checkPermission('coupon_update');

        $row = Coupon::find($id);
        if (empty($row)) {
            return redirect(route('coupon.admin.index'));
        }

        $data = [
            'row' => $row,
            'breadcrumbs' => [
                [
                    'name' => __('All Coupons'),
                    'url' => route('coupon.admin.index'),
                ],
                [
                    'name' => __('Edit Coupon: :name', ['name' => $row->code]),
                ],
            ],
            'page_title' => __('Edit: :name', ['name' => $row->code]),
        ];
        // Make sure we pass apply_to to the view if exists
        if (! empty($row->apply_to)) {
            $data['row']->apply_to = $row->apply_to;
        }

        // جلب بيانات المستخدم من only_for_user
        $userData = null;
        if (! empty($row->only_for_user)) {
            $userIds = is_array($row->only_for_user) ? $row->only_for_user : json_decode($row->only_for_user, true);
            if (! empty($userIds) && is_array($userIds)) {
                $userId = $userIds[0] ?? null;
                if ($userId) {
                    $user = \App\User::find($userId);
                    if ($user) {
                        $userData = [
                            'id' => $user->id,
                            'name' => $user->getDisplayName(),
                            'avatar' => $user->getAvatarUrl(),
                            'phone' => $user->phone ?? '',
                            'email' => $user->email ?? '',
                        ];
                    }
                }
            }
        }
        $data['user'] = $userData;

        // $data['row']['only_for_user'] = $userData;
        // dd($data);
        return view('Coupon::admin.detail', $data);
    }

    public function create(Request $request)
    {
        $this->checkPermission('coupon_create');

        $row = new Coupon;
        $data = [
            'row' => $row,
            'breadcrumbs' => [
                [
                    'name' => __('All Coupons'),
                    'url' => route('coupon.admin.index'),
                ],
                [
                    'name' => __('Create Coupon'),
                ],
            ],
            'page_title' => __('Create Coupon'),
        ];

        return view('Coupon::admin.detail', $data);
    }

    public function store(Request $request, $id)
    {

        // dd($request->all());
        $request->validate([
            'code' => [
                'required',
                'max:50',
                'string',
                'alpha_dash',
                Rule::unique('bravo_coupons')->ignore($id > 0 ? $id : false),
            ],
            'amount' => ['required'],
        ]);

        if ($id > 0) {
            $this->checkPermission('coupon_update');
            $row = Coupon::find($id);
            if (empty($row)) {
                return redirect(route('coupon.admin.index'));
            }
        } else {
            $this->checkPermission('coupon_create');
            $row = new Coupon;
            $row->status = 'publish';
        }

        $dataKeys = [
            'name',
            'code',
            'status',
            'amount',
            'discount_type',
            'end_date',
            'min_total',
            'max_total',
            'services',
            'apply_to',
            'only_for_user',
            'quantity_limit',
            'limit_per_user',
            'image_id',
        ];

        $row->fillByAttr($dataKeys, $request->input());
        // تأكد أن only_for_user دائماً مصفوفة
        if (! empty($request->input('only_for_user'))) {
            $onlyForUser = $request->input('only_for_user');
            if (! is_array($onlyForUser)) {
                $onlyForUser = [$onlyForUser];
            }
            // نظف القيم الفارغة
            $row->only_for_user = array_filter($onlyForUser);
        }

        // If coupon is not for specific user, clear any only_for_user data
        if ($request->input('apply_to') !== 'specific_user') {
            $row->only_for_user = [];
        }

        $res = $row->save();

        // Save Coupon Product only after coupon is saved (so coupon_id is available)
        $services = $request->input('services');
        $coupon_product = new CouponServices;
        $coupon_product->clean($row->id);
        if (! empty($services) and is_array($services)) {
            $services = Service::selectRaw('id,object_id,object_model')->whereIn('id', $services)->get();
            foreach ($services as $service) {
                $coupon_product = new CouponServices;
                $coupon_product->fill([
                    'coupon_id' => $row->id,
                    'object_id' => $service->object_id,
                    'object_model' => $service->object_model,
                    'service_id' => $service->id,
                ]);
                $coupon_product->save();
            }
        }
        if ($res) {

            if ($id > 0) {
                return redirect()->back()->with('success', __('Coupon updated'));
            } else {
                return redirect()->to(route('coupon.admin.index'))->with('success', __('Coupon created'));
            }
        }
    }

    public function bulkEdit(Request $request)
    {
        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or ! is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action) {
            case 'delete':
                foreach ($ids as $id) {
                    $query = Coupon::query()->where('id', $id);
                    $this->checkPermission('coupon_delete');
                    $query->first();
                    if (! empty($query)) {
                        $query->delete();
                    }
                }

                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case 'clone':
                $this->checkPermission('coupon_create');
                foreach ($ids as $id) {
                    (new Coupon)->saveCloneByID($id);
                }

                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = Coupon::query()->where('id', $id);
                    $this->checkPermission('coupon_update');
                    $query->update(['status' => $action]);
                }

                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }

    public function getServiceForSelect2(Request $request)
    {
        $q = $request->query('q');
        $query = Service::select('*');
        if ($q) {
            $query->where(function ($query) use ($q) {
                $query->where('title', 'like', '%'.$q.'%')
                    ->orWhere('id', $q);
            });
        }
        $res = $query->orderBy('id', 'desc')->orderBy('title', 'asc')->limit(20)->get();
        $data = [];
        if (! empty($res)) {
            foreach ($res as $item) {
                $image = null;
                // First try image on the service record itself
                if (! empty($item->image_id)) {
                    $image = get_file_url($item->image_id, 'thumb');
                }
                // Fallback: try the underlying object (tour, hotel, etc.)
                if (empty($image) && ! empty($item->service) && ! empty($item->service->image_id)) {
                    $image = get_file_url($item->service->image_id, 'thumb');
                }
                $data[] = [
                    'id' => $item->id,
                    'text' => $item->title,
                    'image' => $image,
                ];
            }
        }

        return response()->json([
            'results' => $data,
        ]);
    }

    public function getServiceDetails(Request $request)
    {
        $id = $request->query('id');
        if (empty($id)) {
            return response()->json(['status' => 0, 'message' => __('Service id is required')]);
        }
        $service = Service::find($id);
        if (empty($service)) {
            return response()->json(['status' => 0, 'message' => __('Service not found')]);
        }
        $object = $service->service;
        if (empty($object)) {
            return response()->json(['status' => 0, 'message' => __('Related object not found')]);
        }
        // dataForApi(true) returns details for single view
        try {
            $detail = $object->dataForApi(true);
            $detail['image'] = $detail['image'] ?? get_file_url($object->image_id, 'full') ?? get_file_url($service->image_id, 'full');

            return response()->json(['status' => 1, 'data' => $detail]);
        } catch (\Exception $e) {
            return response()->json(['status' => 0, 'message' => $e->getMessage()]);
        }
    }
}
